In [31]:
import pandas as pd
import numpy as np

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Model
from sklearn.neighbors import KNeighborsRegressor

# Evaluation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Save model
import pickle

In [12]:
df = pd.read_csv(r"C:\Users\shash\OneDrive\Desktop\practices\ML_2\assessment\diamonds.csv")
df

       carat        cut color clarity  depth  table     x     y     z  price
0       0.23      Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1       0.21    Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2       0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3       0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4       0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50   2757
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61   2757
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757

[53940 rows x 10 columns]

### Basic informaation fo data set

In [13]:
df.head()

   carat      cut color clarity  depth  table     x     y     z  price
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   x        53940 non-null  float64
 7   y        53940 non-null  float64
 8   z        53940 non-null  float64
 9   price    53940 non-null  int64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [11]:
df.tail()

       carat        cut color clarity  depth  table     x     y     z  price
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50   2757
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61   2757
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757

In [10]:
df.describe()

,carat,depth,table,x,y,z,price
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,5.731157,5.734526,3.538734,3932.799722
std,0.474011,1.432621,2.234491,1.121761,1.142135,0.705699,3989.439738
min,0.200000,43.000000,43.000000,0.000000,0.000000,0.000000,326.000000
25%,0.400000,61.000000,56.000000,4.710000,4.720000,2.910000,950.000000
50%,0.700000,61.800000,57.000000,5.700000,5.710000,3.530000,2401.000000
75%,1.040000,62.500000,59.000000,6.540000,6.540000,4.040000,5324.250000
max,5.010000,79.000000,95.000000,10.740000,58.900000,31.800000,18823.000000

### Define the input features (X) and the target variable (price).

In [14]:
x = df.drop("price", axis =1)
y = df["price"]

### Identify Feature Types

In [18]:
categorical_features = x.select_dtypes(include=['object']).columns
numerical_features = x.select_dtypes(include=['int64', 'float64']).columns

print("Categorical:", categorical_features)
print("Numerical:", numerical_features)

Categorical: Index(['cut', 'color', 'clarity'], dtype='object')
Numerical: Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

### Split the dataset into training and testing sets using a 75:25 ratio.

In [23]:
# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=42)

In [28]:
# Columns Transformer
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(transformers=[("num", StandardScaler(), numerical_features),("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)])

### Build Full Pipeline (Preprocessing + Model)

In [33]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                          ('model',KNeighborsRegressor(n_neighbors=5))])

In [34]:
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['cut', 'color', 'clarity'], dtype='object'))])),
                ('model', KNeighborsRegressor())])

### Train a KNN Regressor model using Scikit-learn

In [35]:
# Model
from sklearn.neighbors import KNeighborsRegressor
pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['cut', 'color', 'clarity'], dtype='object'))])),
                ('model', KNeighborsRegressor())])

### Predictions

In [38]:
y_pred = pipeline.predict(x_test)
y_pred

array([ 586.4, 2427.6, 1083.4, ..., 8944.4, 4548.8, 4121.4])

### Evaluate the model using the following metrics:
- Mean Absolute Error (MAE)
- Root Mean Squared Error (RMSE)
- R² Score

In [39]:
### Mean Absolute Error
mae = mean_absolute_error(y_test, y_pred)
mae

408.16188357434186

In [40]:
### Root Mean Squared Error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rmse

np.float64(785.8675181791344)

In [41]:
### R² Score
r2 = r2_score(y_test, y_pred)
r2

0.9606874684715353

### Save the trained pipeline using Pickle for future use.

In [42]:
with open("diamond_price_model.pkl", "wb") as f:
    pickle.dump(pipeline, f)